### ISSUE TITLE
org-outer-indent--compute-prefixes fails with empty headlines file

### ISSUE THREAD

**Issue by tangrammer** [rougier/org-outer-indent#1]
Hello!
I'm getting `apply: Wrong number of arguments: #<subr max>, 0` with files that haven't headlines, specifically using orgroam.
I could replicate the problem calling `M-x eval-expression` and passing `(org-outer-indent--compute-prefixes)`
I'm going to set up a PR to try to collaborate a bit here :) 

thanks for this library, using your repos my emacs is getting each day better!

**Comment by rougier** [comment]
Thanks for the report and the fix, it has been merged.
